baseURL = "https://cars-project.github.io/"
languageCode = "en-gb"
theme = "winston"
themesDir = "themes"
title = "CARS Project"
paginate = 3
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  twitter_handle = ""
  showAuthorOnHomepage = false
  showAuthorOnPosts = false
  showPostsOnHomepage = true
  addDot = false
  addFrame = true
  highlightColor = '#017dc8'
  baseColor = "#ffffff"
  baseOffsetColor = "#eaeaea"
  headingColor = "#017dc8"
  textColor = "#4e5157"
  dotColor = ""

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
